### ISSUE TITLE
gplus doc: the effective number of genotype

### ISSUE THREAD

**Issue by zzxiang** [gc5k/EigenGWASRDoc#1]
https://github.com/gc5k/EigenGWASRDoc/blob/5ff6cf12798665cdadd2f58c5ebb61fd5860ac4e/dev/gplus.docx

![image](https://user-images.githubusercontent.com/10098144/50050065-aa623200-0134-11e9-9de8-05d89357246b.png)

I think the denotation in the red frame should be changed to 

![image](https://user-images.githubusercontent.com/10098144/50050068-d7164980-0134-11e9-9497-7d8f7b87919a.png)

**Comment by gc5k** [comment]
fixed. thanks.
