### ISSUE TITLE
gplus doc: allele frequency

### ISSUE THREAD

**Issue by zzxiang** [gc5k/EigenGWASRDoc#2]
https://github.com/gc5k/EigenGWASRDoc/blob/5ff6cf12798665cdadd2f58c5ebb61fd5860ac4e/dev/gplus.docx

In _Step 0: Standardization [freq, can be paralleled]_, the allele frequency of the reference allele is denoted as

![image](https://user-images.githubusercontent.com/10098144/50050218-29a53500-0138-11e9-8fa4-bfab71c99623.png)

But if my understanding is right, _n_l_ is the the effective number of genotypes but not alleles, so either a genotype of AA, Aa, or aa should count as 1. Therefore, the definition of _p_l_ should be

![image](https://user-images.githubusercontent.com/10098144/50050241-d5e71b80-0138-11e9-87c2-6c7811d9a366.png)

**Comment by gc5k** [comment]
fixed, thanks
